// Package tests contains black-box tests for the resources package.
// Using package resources_test gives access only to exported symbols,
// which is why CertDER and CertPEMsMatch are exported.
package tests

import (
	"testing"

	"github.com/Christian-Verderame/terraform-provider-verify/internal/resources"
)

// realCertPEM is a valid self-signed cert generated by the provider (demotokensigner).
const realCertPEM = `-----BEGIN CERTIFICATE-----
MIIFFTCCAv2gAwIBAgIRAIVyzhTJjEPJZVxqM1a8fbYwDQYJKoZIhvcNAQELBQAw
NTELMAkGA1UEBhMCVVMxDDAKBgNVBAoTA0lCTTEYMBYGA1UEAxMPZGVtb3Rva2Vu
c2lnbmVyMB4XDTI2MDczMDE2Mzk0OVoXDTI3MDczMDE2NDQ0OVowNTELMAkGA1UE
BhMCVVMxDDAKBgNVBAoTA0lCTTEYMBYGA1UEAxMPZGVtb3Rva2Vuc2lnbmVyMIIC
IjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAunCqsxvG8BRw+jvNX8V6fOXX
ZbQHngPQBHXrpsNmjhrCatTWGPzgynvXmTRqimGozYkx6y1k9rbhVfKtirVeLdtk
w5zo7L90+y8FIXoU2dn3SyPG08G5bBH9JTsYc7DjyTwlcORvrOSsOW+Fv/LfqGHR
6ymNDdpv1RQCae/u2EeFT3MRhr0ctZMV3upj9XQsXisDWAJieCX6Ol8PuM+l6aaU
+fUFl6956vMBG/mJUcQF3IM0Im/zaZGI5vatrtTDE5Kj1/no62w2yrvK7p95Ucsp
02bInHSR2uAejiA2+fOzYIiVSuOQLnZ5a/Xhbfj2KXpu3EcYtABhpunN8uVzMNPZ
R1XGple2+AQaWR3dxWovedUUVKSKR6uav88jwGi0YI5WaNmv3mM2GH0iXUPEt5YL
HdoB4sAHJy0vE2fZJcxIFr04Dwni1Agfm+3kdTxzm327+EX4pmIFpyBSzFQbLfKR
RxqMNPZgurr4c6Oqdcllw6YEL3V/JCm11N7K5btcg9VQhCSG8T4RP2iShEX8yEOF
MkZGRI8z+SjirtcU8O8zqhHQokeZpfAa8qFiuAXlljd1YhSMdomfQ6TmYEQlU0SZ
EWc8qaOBreDDrX3fhyFtOe1rAuOW8cqgdt4TlZjiDjjg+6R9oBXBzeGesdkTqn8m
1weqOeS/ScmtaCW5gNECAwEAAaMgMB4wDgYDVR0PAQH/BAQDAgeAMAwGA1UdEwEB
/wQCMAAwDQYJKoZIhvcNAQELBQADggIBAE2KULBZjQB70YwEUYlMC/rs7QDoaAAj
d2MPBmE1e/36J2vFKooOInks2gkchEoX0JvBy6DZeCrkf0vEJtMukGlqQgmhH1NI
ghLVHFOzZIiGaufZZrqYyOjOCuAUSjKKLqxZAb9kVq0lCFn1XidHFBB2acFOLiFj
IHjIw5JkmxkAt0yTP7xZ+dmGGh5BgKoW3ciCvOjSaWx9kyNeQQ0O08bpUIsqO95A
GmuuAbWrjmQonrDWqF14rVzDDFGk9QM8NIEHWozETAxLt/VoIUYjvv8kolJfMBZs
Fkbj4GVslvjJ9VLP9LOvzl1y54nQagFFp/GuqBs2f2EVxxkvPiXq/R8C+WaydXHL
9YXHNPqEqwQMhD1wdqmw2H3ms9TsLVADGAz5muCGx+BPCqevDwf7NOH+670FBmf4
7OQUTcAT4ETGsuVHYJlXZNfEzXSTzdAGvqEDwA3xQSm/Zt/31ftW4GiT3xqWXihj
NR4fbTm8/jlhH8ZdO3S3ZbgEu83lrVXX7s56ua/KHxBezGPaFlrTUOLVrntXkNxP
pi7TJpxaWBBHosf34nj6Yi3T39jTxJHL7NiUhpVzdh48sJNnap5gtWJNpMguezCN
ksXmtFD9vx8aodLLgYZZzFU8B+C/n6Vy5u+0ZgUk/oKnn3eud/WTpyQfdNQnRCRe
7B2JLnAWkZlz
-----END CERTIFICATE-----`

func TestCertDER_validPEM(t *testing.T) {
	der := resources.CertDER(realCertPEM)
	if der == nil {
		t.Fatal("expected non-nil DER for valid cert PEM")
	}
	if len(der) == 0 {
		t.Error("expected non-empty DER bytes")
	}
}

func TestCertDER_emptyString(t *testing.T) {
	if resources.CertDER("") != nil {
		t.Error("expected nil for empty PEM")
	}
}

func TestCertDER_garbage(t *testing.T) {
	if resources.CertDER("not a pem at all") != nil {
		t.Error("expected nil for garbage input")
	}
}

func TestCertDER_truncatedPEM(t *testing.T) {
	// A PEM header with no valid DER body — pem.Decode succeeds but
	// x509.ParseCertificate must fail, returning nil.
	const bad = `-----BEGIN CERTIFICATE-----
dGhpcyBpcyBub3QgYSBjZXJ0
-----END CERTIFICATE-----`
	if resources.CertDER(bad) != nil {
		t.Error("expected nil for PEM with non-certificate content")
	}
}

func TestCertPEMsMatch_identical(t *testing.T) {
	if !resources.CertPEMsMatch(realCertPEM, realCertPEM) {
		t.Error("identical PEMs should match")
	}
}

func TestCertPEMsMatch_identicalWithExtraWhitespace(t *testing.T) {
	// Extra leading newline — DER bytes are identical, should still match.
	withNewline := "\n" + realCertPEM
	if !resources.CertPEMsMatch(realCertPEM, withNewline) {
		t.Error("PEMs with different whitespace but same DER should match")
	}
}

func TestCertPEMsMatch_differentCerts(t *testing.T) {
	if resources.CertPEMsMatch(realCertPEM, "garbage") {
		t.Error("valid cert vs garbage should not match")
	}
}

func TestCertPEMsMatch_bothEmpty(t *testing.T) {
	if resources.CertPEMsMatch("", "") {
		t.Error("two empty strings should not match")
	}
}

func TestCertPEMsMatch_oneEmpty(t *testing.T) {
	if resources.CertPEMsMatch(realCertPEM, "") {
		t.Error("valid cert vs empty should not match")
	}
}
