terraform {
  required_providers {
    verify = {
      source = "christian-verderame/verify"
    }

    random = {
      source = "hashicorp/random"
    }
  }
}

provider "verify" {}

# -------------------------------------------------------------------
# The certificate and private key live in examples/certificates/ and
# are generated once by examples/cert/. Run that root first, upload
# certificates/cert.pem to IBM Verify, then run this root as many
# times as needed — the key never changes.
# -------------------------------------------------------------------

# Read the private key from the path supplied in terraform.tfvars.
# If the file does not exist, run: cd examples/cert && terraform apply
locals {
  private_key_pem = file(var.private_key_path)
}

variable "private_key_path" {
  type        = string
  description = "Path to the RSA private key PEM file generated by examples/cert/."
  default     = "./certificates/key.pem"
}

# keepers forces a new UUID whenever any JWT input changes — issuer, subject,
# or key_id. Without this, changing jwt_subject in terraform.tfvars would reuse
# the old jti UUID, causing IBM Verify to reject it with CSIAQ5206E (jti replay).
resource "random_uuid" "jwt_id" {
  keepers = {
    issuer  = var.jwt_issuer
    subject = var.jwt_subject
    key_id  = var.jwt_key_id
  }
}

# Sign a fresh JWT on every apply using the stable private key.
# The JWT is short-lived (15 min) but the key pair never rotates,
# so IBM Verify can always verify the signature with the cert it has.
resource "verify_jwt" "custom" {
  issuer             = var.jwt_issuer
  subject            = var.jwt_subject
  key_id             = var.jwt_key_id
  jwt_id             = random_uuid.jwt_id.result
  private_key_pem    = local.private_key_pem
  expires_in_seconds = 900
}

output "jwt" {
  value     = verify_jwt.custom.token
  sensitive = true
}

output "jwt_issued_at" {
  value = verify_jwt.custom.issued_at
}

output "jwt_expires_at" {
  value = verify_jwt.custom.expires_at
}

variable "verify_tenant_url" {
  type        = string
  description = "IBM Verify tenant URL."
}

variable "sts_client_id" {
  type        = string
  description = "IBM Verify STS client ID."
}

variable "sts_client_secret" {
  type        = string
  description = "IBM Verify STS client secret."
  sensitive   = true
}

# JWT claim variables — set these in terraform.tfvars to match your
# IBM Verify tenant configuration.
variable "jwt_issuer" {
  type        = string
  description = "Value placed in the JWT iss claim."
}

variable "jwt_subject" {
  type        = string
  description = "IBM Verify Cloud Directory username placed in the JWT sub claim."
}

variable "jwt_key_id" {
  type        = string
  description = "Certificate label in IBM Verify placed in the JWT kid header."
}

resource "verify_token_exchange" "example" {
  tenant_url    = var.verify_tenant_url
  client_id     = var.sts_client_id
  client_secret = var.sts_client_secret
  subject_token = verify_jwt.custom.token

  # IBM Verify STS clients can be configured with a custom token type URN
  # instead of the standard RFC 8693 urn:ietf:params:oauth:token-type:jwt.
  # This tenant requires the custom URN below — change it to match whatever
  # is configured under Security → API clients → STS → Token exchange settings.
  subject_token_type = "urn:demo:token-type:user-jwt"
}

output "access_token" {
  value     = verify_token_exchange.example.access_token
  sensitive = true
}

output "access_token_expires_in" {
  value = verify_token_exchange.example.expires_in
}

output "issued_token_type" {
  value = verify_token_exchange.example.issued_token_type
}

output "token_type" {
  value = verify_token_exchange.example.token_type
}

output "grant_id" {
  value = verify_token_exchange.example.grant_id
}

output "scope" {
  value = verify_token_exchange.example.scope
}






# data source — re-evaluated on every plan/apply so the result always
# reflects the live token status, not a cached value from a previous run.
data "verify_token_introspection" "example" {
  tenant_url    = var.verify_tenant_url
  client_id     = var.sts_client_id
  client_secret = var.sts_client_secret
  token         = verify_token_exchange.example.access_token
}

output "token_active" {
  value = data.verify_token_introspection.example.active
}

output "introspected_subject" {
  value = data.verify_token_introspection.example.subject
}

output "introspected_username" {
  value = data.verify_token_introspection.example.username
}

output "introspected_preferred_username" {
  value = data.verify_token_introspection.example.preferred_username
}

output "introspected_name" {
  value = data.verify_token_introspection.example.name
}

output "introspected_given_name" {
  value = data.verify_token_introspection.example.given_name
}

output "introspected_scope" {
  value = data.verify_token_introspection.example.scope
}

output "introspected_expires_at" {
  value = data.verify_token_introspection.example.expires_at
}
