# IBM Verify tenant URL — e.g. https://example.verify.ibm.com
verify_tenant_url = "https://ChrisVerde02.verify.ibm.com"

# STS API client credentials
sts_client_id     = "9ada0c66-b6e9-4fdb-a6c8-62156f5ae533"
sts_client_secret = "TvFt1rBA9gMBHYM8W5Rq"

# Path to the RSA private key generated by examples/cert/.
# Run: cd examples/cert && terraform apply
# The default points to the certificates/ directory alongside this file.
private_key_path  = "./certificates/key.pem"

# JWT claim values — must match your IBM Verify tenant configuration.
# jwt_issuer: any URL that identifies this system as the token issuer.
# jwt_subject: the IBM Verify Cloud Directory username to authenticate as.
# jwt_key_id: the certificate label set when uploading cert.pem to IBM Verify.
jwt_issuer  = "https://demo.ibm.com"
jwt_subject = "bretton"
jwt_key_id  = "demotokensigner"